#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
input_template.py

Created by Charlie Murphy
17 December 2021

This file is used to give the correct file paths to create_ensemble.py
'''

# New_graphs
new_graphs = False

# Graph File
# This file must have been previously generated by pickling. If new_graphs is 
# False this data will be used. Otherwise data will be pulled from the shapefiles
graph_dump = "Test.dump"

# SHP file with vtds
vtd_file  = r'C:\Users\charl\Box\Internships\Gerry Chain 2\States\Pennsylvania\2021 Data Set 2 Edited\PA_2020_vtds.shp'

# SHP file with counties
county_file = r'C:\Users\charl\Box\Internships\Gerry Chain 2\States\Pennsylvania\2021 Data Set 2 Edited\PA_2020_counties.shp'

# SHP file with municipalities
muni_file = r'C:\Users\charl\Box\Internships\Gerry Chain 2\States\Pennsylvania\2021 Data Set 2 Edited\PA_2020_muni.shp'

# Destination folder for ensemble.  
# Must be placed within the Ensembles folder
folder = 'Testing'

# File name
filename = "Test_1"

# GEOID Column
geoid_col = 'GEOID20'

# Population Column
pop_col = 'P0010001'

# County Column
county_col = 'FIPS'

# Municipality Column
muni_col = "MUNI"

# Name Column
name_col = "NAME"

# Geometry Column
geom_col = "geometry"

# Assignment Column
# Name of the column in the graph objects that will be used to record the 
# redistricting plan
assignment_col = 'assignment'

# Starting County
# The number in the county_col of the starting county. The population of this 
# county must be greater than (1 + epsilon) * the ideal population and have
# more
starting_county = '049'

# Epsilon
# The percentage any given district is allowed to be different from the ideal
# population. Note that this does not apply to the final district.
epsilon = 0.05

# Number of Districtsx`
district_num = 10

# Number of plans
runs = 1

# DOF Max
# The maximum number of nodes at a given divided level (county, muni, or vtd) 
# that any additional node may be from first node allocated to that district.
# This parameter is not used to restrict the plan and should be kept arbitrarily
# high. If this parameter is too low it may cause unexpected behavior
dof_max = 50